# Generated by Django 4.2.7 on 2023-11-30 11:26

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('path_crumb', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Name')),
                ('hex_code', models.CharField(help_text='A hex code for the desired color shade. It starts with # and contains 6 characters. Visit https://www.w3schools.com/colors/colors_picker.aspto find out more.', max_length=7, unique=True, verbose_name='Hex color code')),
            ],
        ),
        migrations.CreateModel(
            name='ParentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='An optional description.', null=True, verbose_name='Description')),
                ('fabric_info', models.TextField(blank=True, help_text='An optional description of fabric care, composition of the fabric, etc.', null=True, verbose_name='Information about fabric')),
                ('sizes_info', models.TextField(blank=True, help_text='An optional description of sizes,f.e. chest width in size 38: 92 cm.', null=True, verbose_name='Information about sizes')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Parent Products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(help_text="f.e.: 'polka dot', 'royal blue' or just simply 'black'.", max_length=15, verbose_name='Style')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Discounted price')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=192, unique=True)),
                ('main_image_url', models.ImageField(upload_to='products/', verbose_name='Main image')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of views')),
                ('color', models.ForeignKey(help_text='Color used for filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color', verbose_name='Color')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.parentproduct', verbose_name='Parent Product')),
            ],
            options={
                'ordering': ('views',),
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Name')),
            ],
            options={
                'ordering': ('group', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SizeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="f.e. 'numerical', 'literal'.", max_length=15, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.size', verbose_name='Size')),
            ],
        ),
        migrations.AddField(
            model_name='size',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.sizegroup', verbose_name='Related Size Group'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(through='products.Stock', to='products.size', verbose_name='Sizes'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='products/', verbose_name='Image url')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('parent', 'style'), name='unique_parent_style'),
        ),
    ]
